---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.15.8
    go_checksum: sha256:d3379c32a90fdf9382166f8f48034c459a8cc433730bc9476d39d9082c94583b
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
