---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Detect architecture
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - name: Upgrade vulkan-sdk
      import_tasks: "tasks/vulkan-sdk.yaml"
      vars:
        uninstall_previous_version: true
        vulkansdk_path: /opt/local/vulkan-sdk
      when: arch == 'amd64'
    - name: Install golang
      import_tasks: "tasks/golang.yaml"
      vars:
        go_version: 1.26.0
        go_checksum_amd64: sha256:aac1b08a0fb0c4e0a7c1555beb7b59180b05dfc5a3d62e40e9de90cd42f88235
        go_checksum_arm64: sha256:bd03b743eb6eb4193ea3c3fd3956546bf0e3ca5b7076c8226334afe6b75704cd
        go_path: /opt/local
