---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.17
    go_checksum: sha256:6bf89fc4f5ad763871cf7eac80a2d594492de7a818303283f1366a7f6a30372d
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
