---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Detect architecture
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - name: Install golang
      import_tasks: "tasks/golang.yaml"
      vars:
        go_version: 1.25.5
        go_checksum_amd64: sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b
        go_checksum_arm64: sha256:b00b694903d126c588c378e72d3545549935d3982635ba3f7a964c9fa23fe3b9
        go_path: /opt/local
