---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.16.1
    go_checksum: sha256:3edc22f8332231c3ba8be246f184b736b8d28f06ce24f08168d8ecf052549769
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
