---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.18
    go_checksum: sha256:e85278e98f57cdb150fe8409e6e5df5343ecb13cebf03a5d5ff12bd55a80264f
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
