---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.14.6
    go_checksum: sha256:5c566ddc2e0bcfc25c26a5dc44a440fcc0177f7350c1f01952b34d5989a0d287
    gcc_version: 10.2.0
    gcc_checksum: sha256:27e879dccc639cd7b0cc08ed575c1669492579529b53c9ff27b0b96265fa867d
    gcc_prefix_dir: /opt/local
    gcc_mirror: ftp://ftp.gwdg.de/pub/misc/gcc/releases/
  tasks:
    - name: Install gcc
      include: "tasks/gcc.yaml"
      #    - name: Install golang
      #      include: "tasks/golang.yaml"
