---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.19.3
    go_checksum: sha256:74b9640724fd4e6bb0ed2a1bc44ae813a03f1e72a4c76253e2d5c015494430ba
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
