---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.15.7
    go_checksum: sha256:0d142143794721bb63ce6c8a6180c4062bcf8ef4715e7d6d6609f3a8282629b3
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
