---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.18.1
    go_checksum: sha256:b3b815f47ababac13810fc6021eb73d65478e0b2db4b09d348eefad9581a2334
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
