---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Detect architecture
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - name: Upgrade vulkan-sdk
      import_tasks: "tasks/vulkan-sdk.yaml"
      vars:
        vulkansdk_path: /opt/local/vulkan-sdk
      when: arch == 'amd64'
    - name: Install golang
      import_tasks: "tasks/golang.yaml"
      vars:
        go_version: 1.25.4
        go_checksum_amd64: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
        go_checksum_arm64: sha256:a68e86d4b72c2c2fecf7dfed667680b6c2a071221bbdb6913cf83ce3f80d9ff0
        go_path: /opt/local
