---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.15
    go_checksum: sha256:2d75848ac606061efe52a8068d0e647b35ce487a15bb52272c427df485193602
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
