---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.20.1
    go_checksum: sha256:000a5b1fca4f75895f78befeb2eecf10bfff3c428597f3f1e69133b63b911b02
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
