---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.17.5
    go_checksum: sha256:bd78114b0d441b029c8fe0341f4910370925a4d270a6a590668840675b0c653e
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
