---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.17.2
    go_checksum: sha256:f242a9db6a0ad1846de7b6d94d507915d14062660616a61ef7c808a76e4f1676
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
