---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.19
    go_checksum: sha256:464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
