---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.18.2
    go_checksum: sha256:e54bec97a1a5d230fc2f9ad0880fcbabb5888f30ed9666eca4a91c5a32e86cbc
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
