---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.18.3
    go_checksum: sha256:956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
