---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.16.2
    go_checksum: sha256:542e936b19542e62679766194364f45141fde55169db2d8d01046555ca9eb4b8
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
