---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.17.7
    go_checksum: sha256:02b111284bedbfa35a7e5b74a06082d18632eff824fd144312f6063943d49259
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
