---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Detect architecture
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - name: Upgrade vulkan-sdk
      import_tasks: "tasks/vulkan-sdk.yaml"
      vars:
        uninstall_previous_version: true
        vulkansdk_path: /opt/local/vulkan-sdk
      when:
        lookup('ansible.builtin.env', 'NOVULKAN', default='0') != '1' and
        arch == 'amd64'
    - name: Install golang
      import_tasks: "tasks/golang.yaml"
      vars:
        go_version: 1.26.5
        go_checksum_amd64: sha256:5c2c3b16caefa1d968a94c1daca04a7ca301a496d9b086e17ad77bb81393f053
        go_checksum_arm64: sha256:fe4789e92b1f33358680864bbe8704289e7bb5fc207d80623c308935bd696d49
        go_path: /opt/local
      when:
        lookup('ansible.builtin.env', 'NOGO', default='0') != '1'
