---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.20.4
    go_checksum: sha256:698ef3243972a51ddb4028e4a1ac63dc6d60821bf18e59a807e051fee0a385bd
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
