---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Detect architecture
      set_fact:
        arch: "{{ 'arm64' if ansible_facts.architecture == 'aarch64' else 'amd64' }}"
    - name: Upgrade vulkan-sdk
      import_tasks: "tasks/vulkan-sdk.yaml"
      vars:
        uninstall_previous_version: true
        vulkansdk_path: /opt/local/vulkan-sdk
      when:
        lookup('ansible.builtin.env', 'NOVULKAN', default='0') != '1' and
        arch == 'amd64'
    - name: Install golang
      import_tasks: "tasks/golang.yaml"
      vars:
        go_version: 1.26.4
        go_checksum_amd64: sha256:1153d3d50e0ac764b447adfe05c2bcf08e889d42a02e0fe0259bd47f6733ad7f
        go_checksum_arm64: sha256:ef758ae7c6cf9267c9c0ef080b8965f453d89ab2d25d9eb22de4405925238768
        go_path: /opt/local
      when:
        lookup('ansible.builtin.env', 'NOGO', default='0') != '1'
