---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.14.7
    go_checksum: sha256:4a7fa60f323ee1416a4b1425aefc37ea359e9d64df19c326a58953a97ad41ea5
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
