---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install golang
      import_tasks: "tasks/golang.yaml"
      vars:
        go_version: 1.22.1
        go_checksum: sha256:aab8e15785c997ae20f9c88422ee35d962c4562212bb0f879d052a35c8307c7f
        go_path: /opt/local
