---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.17.1
    go_checksum: sha256:dab7d9c34361dc21ec237d584590d72500652e7c909bf082758fb63064fca0ef
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
