---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install golang
      import_tasks: "tasks/golang.yaml"
      vars:
        go_version: 1.22.3
        go_checksum: sha256:8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36
        go_path: /opt/local
