---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.17.6
    go_checksum: sha256:231654bbf2dab3d86c1619ce799e77b03d96f9b50770297c8f4dff8836fc8ca2
    go_path: /opt/local
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
