---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    go_version: 1.16.5
    go_checksum: sha256:b12c23023b68de22f74c0524f10b753e7b08b1504cb7e417eccebdd3fae49061
  tasks:
    - name: Install golang
      include: "tasks/golang.yaml"
