###
### Install/Upgrade golang
###
- name: query current golang version
  command: grep "go{{ go_version }}" "{{ go_path }}/go/VERSION"
  register: checked_go
  changed_when: "checked_go.rc != 0"
  failed_when: false
  check_mode: no

- block:
    - name: configure archive filename
      set_fact:
        go_archive: "go{{ go_version }}.linux-{{ arch }}.tar.gz"
    - name: download golang
      get_url:
        dest: /tmp
        url: "https://dl.google.com/go/{{ go_archive }}"
        checksum: "{{ lookup('ansible.builtin.vars', 'go_checksum_' + arch) }}"
    - name: create installation directory
      file:
        path: "{{ go_path }}"
        state: directory
    - name: remove old golang install
      file:
        path: "{{ go_path }}/go"
        state: absent
    - name: unpack golang
      unarchive:
        copy: no
        dest: "{{ go_path }}"
        src: "/tmp/{{ go_archive }}"
      ignore_errors: '{{ ansible_check_mode }}'
    - name: remove golang archive
      file:
        state: absent
        path: "/tmp/{{ go_archive }}"
    - name: setup golang path
      copy:
        content: "PATH=$PATH:{{ go_path }}/go/bin"
        dest: /etc/profile.d/golang.sh
  when: checked_go.rc != 0
